# -*- coding: utf-8 -*-
"""Osteoporosis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Y7W0T3OUSD_Bp4epqDpeNnqbK2yowgaa
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

data = pd.read_csv("osteoporosis.csv")
x = data.iloc[:, :-1].values
y = data.iloc[:, -1].values

data.info()

data.head()

data.isnull().sum()